name: scara
channels:
  - loopbio
  - pkgw-forge
  - ericmjl
  - pytorch
  - conda-forge
  - hcc
dependencies:
  - python=3.8
  - pybind11=2.5.0
  - cython
  - pyyaml
  - colorama
  - flask
  - requests
  - coverage
  - click
  - simplejson
  - pyserial
  - sympy
  - colour
  - jupyter
  - bokeh
  - ffmpeg
  - imutils
  - pip
  - pip:
    - numba==0.50.1
    - clifford==1.3.1
    - opencv-python==4.3.0.36
    - python-socketio==4.6.0
    - flask-socketio==4.3.1
    - git+https://github.com/dry-python/returns.git

#https://github.com/NxRLab/ModernRobotics/tree/master/packages/Python