#pragma once
enum class HomingState {
    // ROTARY
    HOMING_NOT_STARTED,
    ROTARY_MOVE_UNTIL_NO_SENSOR_READ,
    ROTARY_FIND_FIRST_SENSOR_READ,
    ROTARY_READ_UNITIL_SENSOR_NO_LONGER_SENSES,
    ROTARY_REVERSE_DIRECTION_HALF_THE_STEPS,
    HOMING_FINISHED,

    // LINEAR
    LINEAR_MOVE_UNITL_BOTTOM_END_STOP,
    LINEAR_MOVE_UNTIL_TOP_END_STOP,
    LINEAR_MOVE_TO_HALF
};